### ISSUE TITLE
/pollster/api/charts now takes a "page" parameter

### ISSUE THREAD

**Issue by adamhooper** [rOpenGov/pollstR#10]
Hiya,

I maintain Pollster. Hi! I was informed of this project from a user.

I recently added a "page" parameter to http://elections.huffingtonpost.com/pollster/api/charts because it was growing too large. I noticed your fantastic documentation mentions a "page" parameter for `pollstr_polls()`. Could you please create and document the "page" parameter in `pollstr_charts()`?

This project looks great. This probably isn't the last you'll hear from me :).

**Comment by jrnold** [comment]
Nice to meet you, and thanks for letting me know about the API changes! It's sometimes hard for me to keep up with what's going on. Honestly, I"m surprised there haven't been more issues this election cycle. 

It's fixed on github, and I'll have a new version up on CRAN soon. 

Let me know if there's anything else I can do to!
