### ISSUE TITLE
Missing Clinton Poll Value from 6/28

### ISSUE THREAD

**Issue by elliottevans** [rOpenGov/pollstR#14]
A Gravis Marketing/OANN poll that concluded on 6/28 had Trump at 47 and Clinton at 48 in PA. After searching through the 2016 polls in R,

temp1<-pollstr_polls(topic='2016-president',showall=FALSE,state='PA',max_pages=50)
temp2<-temp1$polls
temp3<-temp1$question

we see that there's only one entry for that Gravis Marketing poll (Trump's 47), when there **should also be a row for Clinton's 48.** We find the same thing happening with that same poll in OH, where Trump has a value but Clinton doesn't. This will effect any analysis that incorporates that poll.

**Comment by jrnold** [comment]
I think this is an issue with the Pollster API. Using the development version of pollster, I can't find more than 17 results (2 pages) of results matching that query, not of which include Gravis.
```r
temp1 <- pollstr_polls(topic='2016-president',showall=FALSE,state='PA',max_pages=50)
select(temp1[["polls"]], pollster)
```
```
# A tibble: 17 x 1
                                                                     pollster
                                                                        <chr>
1                                                       Gravis Marketing/OANN
2                                                              NBC/WSJ/Marist
3                                                                  Quinnipiac
4                           GQR (D-Democracy Corps/Women's Voices Women Vote)
5  PPP (D-Americans United for Change/Constitutional Responsibility Project) 
6                                                                  Quinnipiac
7                                                                     PPP (D)
8                                                                  Quinnipiac
9                                                              NBC/WSJ/Marist
10                                                                   Fox News
11                                                                 Quinnipiac
12                                              Franklin and Marshall College
13                                                      Mercyhurst University
14                                                   Robert Morris University
15                                                                    PPP (D)
16                                                                 Quinnipiac
17                                                                 Quinnipiac
```

And these results are confirmed by directly using the API with http://elections.huffingtonpost.com/pollster/api/polls?page=3&state=PA&topic=2016-president&showall=false.

**Comment by adamhooper** [comment]
I'm confused. The first row is Gravis. What am I misreading? I think it would help to see some code that does something we wouldn't expect.

**Comment by jrnold** [comment]
Oops, well, whatever the case is, the problems are not with the code in this package.

**Comment by jrnold** [comment]
A new version is going up on CRAN. Let me know if you keep having problems.
