### ISSUE TITLE
polls method (Not any issue, but a question)

### ISSUE THREAD

**Issue by elliottmorris** [rOpenGov/pollstR#15]
After I run a polls query (using this specification: 

"pollstr_polls(page = 1, chart = NULL, state = NULL, topic = '2016-president',
              question = NULL, before = NULL, after = '2016-07-17', sort = FALSE,
              showall = NULL, max_pages = Inf, convert = TRUE)"

how do I list the polls and their values for each candidate?

**Comment by jrnold** [comment]
```r
library(pollstR)
polls <- pollster_polls(page = 1, chart = NULL, state = NULL, topic = '2016-president',
question = NULL, before = NULL, after = '2016-07-17', sort = FALSE,
showall = NULL, max_pages = Inf, convert = TRUE)
```

The object returned by `pollster_polls` is a list of data frames, so you can find the values in `polls[["questions"]]`. You can merge that data frame with `polls[["polls"]]` to select what you want.

However, you may find the `pollster_chart_data` function more useful: it includes relevant polls from one of Pollster's charts. For example,
```r
pollster_chart_data("2016-general-election-trump-vs-clinton")
```
There is some additional cleaning that HuffPost Pollster does to make the various questions and polls standardized, so it's easier to use if it fits your use case.

**Comment by elliottmorris** [comment]
Okay! Thanks. 

1 more question: Is it providing me with house-effect corrected values for each poll?

**Comment by jrnold** [comment]
No. Though you can get those for a specific chart using the `pollster_house_effects` function
