### ISSUE TITLE
Issue pulling data

### ISSUE THREAD

**Issue by davidwang95** [rOpenGov/pollstR#17]
I am trying to do a fairly simple query of aggregating all pre-election polls for the 2010 US Senate elections. I have tried the below code and gotten errors with each:

WA_Sen=pollster_polls(chart = "10-WA-Sen-GE-RvM")
WA_Sen$questions
returns "NULL"

WA_Sen$content
returns a list of all responses that are outside the query (such as Trump approval, France election, etc.)

polls <- pollster_polls(page = 1, chart = NULL, state = NULL, topic = '2010-senate',
                        question = NULL, before = NULL, after = NULL, sort = NULL,
                        showall = NULL, max_pages = Inf, convert = TRUE)
polls$questions
returns "NULL"

pollster_chart_data("10-WA-Sen-GE-RvM")
returns "could not find function "pollstr_chart_data""

pollster_polls_slug("10-WA-Sen-GE-RvM")
returns "failed with status code 404"

I am unsure where the issue is as I have tried all these queries with a variety of elections, but the results are all the same. I appreciate the help!

**Comment by jrnold** [comment]
Where is `10-WA-Sen-GE-RvM` coming from? It doesn't look like a chart with that slug exists: http://elections.huffingtonpost.com/pollster/10-WA-Sen-GE-RvM. PollstR redid its API recently, so anything using code or even chart names from before January 2017 will almost certainly not work.

This also didn't show any chart with "WA" in it:
```
library("pollstR")
library("stringr")
library("purrr")
charts <- pollster_charts_iter(.max_pages = 10000)
str_subset(map_chr(charts, "slug"), "WA")
```

What version of pollstR are you using? There isn't a `pollster_chart_data` function in the current `pollstR`. 

There is no `questions` items in `WA_Sen` and the `content` is returning exactly what it should.  This will get all polls that have a question used in a chart, but each poll may have questions that are used in many different charts. This is the main reason pollstR changed the API. You shouldn't search for polls with a chart parameter, If you want the data in a chart you should use the `pollster_charts_polls` function. 

The `pollstR` package is a pretty thin wrapper to the pollstR API: so you should consult the API documentation: https://app.swaggerhub.com/api/huffpostdata/pollster-api/2.0.0.

**Comment by davidwang95** [comment]
On the Huffington Post Pollster website, I was unable to get any data 2010 and prior by manually downloading the CSV files. I am using the API to check if it's an interface error or if the files simply don't exist. I tried guessing the format of 2010 Senate races based on the slug of 2014 files I was able to get (which is how I guessed 10-WA-Sen-GE-RvM). 

I guess my main question is if it is possible to even get 2010 data. Given that you mentioned using code or chart names from before January 2017 will almost certainly not work, do you think it is possible? If not, do you think it would be possible to get the data via Python? Apologies if my questions sound rudimentary -- this is my first time applying R with an API. Thanks!

**Comment by jrnold** [comment]
If it's not in the API, then there's no way to get it. It's not that the API isn't providing access to it, it's that Huffpost wasn't collecting that data. From their [FAQ](http://elections.huffingtonpost.com/pollster/faq), it looks like they didn't start gathering data until in 2010.

**Comment by davidwang95** [comment]
Makes sense. Thank you for the help!
