### ISSUE TITLE
Unfork repo from dlinzer/pollstR

### ISSUE THREAD

**Issue by jrnold** [rOpenGov/pollstR#7]
This repo still a fork of @dlinzer for historical reasons. This effectively makes it hidden on github search. That's actually the reason I wrote my own; because, I didn't realize that rOpenGov had an active fork. Since this is the active version, I think we should unfork it.

**Comment by leeper** [comment]
@jrnold Apparently I will have to make a new repo and we can push to there. (I would rename or delete this one.) Is that going to be a problem (e.g., because it loses issue history)?

**Comment by dlinzer** [comment]
Hey guys,

Please do whatever you need with respect to my repo.  I've been meaning to
take it down anyway and update the readme to direct to
https://github.com/rOpenGov/pollstR.

Let me know if there's anything else I can do to help.

Drew

**Comment by dlinzer** [comment]
Please do whatever you need with respect to my repo.  I've been meaning to take it down anyway and update the readme to direct to https://github.com/rOpenGov/pollstR. Let me know if there's anything else I can do to help.

**Comment by leeper** [comment]
@dlinzer Easiest thing actually would be to just delete your repo (as that will remove the "forked from" note), but no pressure.

**Comment by dlinzer** [comment]
That's fine, I'll do it now.

**Comment by jrnold** [comment]
Great! Thanks Drew!

**Comment by jrnold** [comment]
And now is forked from [isomorphisms](https://github.com/isomorphisms/pollstR) for some reason. Did you try contacting github support? I did that and got this reply

> > Could rOpenGov/pollstr be unforked from dlinzer/pollstr? Currently the version on rOpenGov is the main version, as it is the one being maintained and distributed over CRAN - the official repository for R packages (https://cran.r-project.org/web/packages/pollstR/index.html). Having it as a fork makes it difficult to find on github, as the the original repository appears first.
> 
> Hello Jeffrey,
> 
> We can certainly do that, but for security reasons we will need the permission of one of the owners of the organisation.
> 
> Currently you are only a member.
> 
> If you can get one of the owners to make this request then we can detach the repository.

**Comment by leeper** [comment]
I sent them an email.

**Comment by leeper** [comment]
Done.
